### ISSUE TITLE
Question: Apollo-Server -> Graphql-Yoga recent change

### ISSUE THREAD

**Issue by AMO-MTSY** [maticzav/gimb-events#68]
Hello,
This is just a question: you switched to graphql-yoga fron apollo-server?
I was wandering if you don't wan't to rely anymore on "makeexecutableschema" and keep good integration with "graphql-shield"???

**Comment by maticzav** [comment]
@AMO-MTSY thank you for your question. I made this change because I had trouble integrating `Apollo Server` with `graphqlgen`. Regarding the `graphql-shield` compatibility, GraphQL Yoga ships with `graphql-middleware` out of the box (unlike Apollo Server apollographql/apollo-server#1603). That's where I am importing GraphQL Shield.

**Comment by AMO-MTSY** [comment]
Thanks to you @maticzav for sharing and insight.
I tried graphql-shield with graphql-middleware,  makeexecutableschema and apollo-server-express. It works for me. I'm trying to get many-apollos-over-one-express working with graphql-shield.
